spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
server:
    port: ${SERVER_PORT:8080}

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}

